### ISSUE TITLE
Buttons inactive on some page layouts

### ISSUE THREAD

**Issue by andreiShevelevDC** [n3r4zzurr0/canvas-liquid-effect#1]
**Desktop Chrome 103 on MacOS:**
On width <=1024 px the page layout changes and the buttons become inactive: do not register clicks, cursor doesn't change on hover.
**Mobile Chrome 103 on Android 9:**
On vertical screen only Time Speed button is working, on horizontal - no button is working

**Comment by n3r4zzurr0** [comment]
Thanks for pointing it out.
I have updated the `z-index` value of the parent element that contains all the controls.
